namespace Partialor;

/// <summary>
/// Source texts.
/// </summary>
public static class SourceCodeText {
    /// <summary>
    /// Disclaimer text.
    /// </summary>
    public const string Disclaimer = """
    //------------------------------------------------------------------------------
    // <auto-generated>
    //     This code was generated from a template.
    //
    //     Manual changes to this file may cause unexpected behavior in your application.
    //     Manual changes to this file will be overwritten if the code is regenerated.
    // </auto-generated>
    //------------------------------------------------------------------------------

    """;
}